CREATE TABLE clientes (
    id BIGINT PRIMARY KEY,
    tipo_cliente VARCHAR(20) NOT NULL
);

CREATE TABLE productos (
    id BIGINT PRIMARY KEY,
    precio DOUBLE NOT NULL
);

CREATE TABLE inventario (
    producto_id BIGINT PRIMARY KEY,
    stock INT NOT NULL
);

CREATE TABLE facturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    monto DOUBLE NOT NULL,
    pagada BOOLEAN NOT NULL
);

CREATE TABLE pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    subtotal DOUBLE NOT NULL,
    descuento DOUBLE NOT NULL,
    impuesto DOUBLE NOT NULL,
    total DOUBLE NOT NULL,
    fecha TIMESTAMP NOT NULL,
    estado VARCHAR(30) NOT NULL
);

CREATE TABLE detalle_pedido (
    pedido_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad INT NOT NULL
);